--Drop de todas las tablas, sps y schema
DROP TABLE LOW_STRESS_DESIGN.pasaje_butaca
DROP TABLE LOW_STRESS_DESIGN.pasaje
DROP TABLE LOW_STRESS_DESIGN.vuelo
DROP TABLE LOW_STRESS_DESIGN.ruta_aerea
DROP TABLE LOW_STRESS_DESIGN.butaca
DROP TABLE LOW_STRESS_DESIGN.avion
DROP TABLE LOW_STRESS_DESIGN.factura
DROP TABLE LOW_STRESS_DESIGN.estadia
DROP TABLE LOW_STRESS_DESIGN.habitacion
DROP TABLE LOW_STRESS_DESIGN.hotel
DROP TABLE LOW_STRESS_DESIGN.servicio
DROP TABLE LOW_STRESS_DESIGN.compra
DROP TABLE LOW_STRESS_DESIGN.tipo_habitacion
DROP TABLE LOW_STRESS_DESIGN.cliente
DROP TABLE LOW_STRESS_DESIGN.ciudad
DROP TABLE LOW_STRESS_DESIGN.sucursal
DROP TABLE LOW_STRESS_DESIGN.empresa

DROP PROCEDURE LOW_STRESS_DESIGN.SP_MIGRATION_SCHEMA
DROP SCHEMA LOW_STRESS_DESIGN

--Get column length
SELECT MAX(LEN(BUTACA_TIPO)) FROM gd_esquema.Maestra;


--DROP tablas de BI

DROP TABLE LOW_STRESS_DESIGN.fact_table_pasaje;
DROP TABLE LOW_STRESS_DESIGN.fact_table_estadia;
DROP TABLE LOW_STRESS_DESIGN.bi_tipo_pasaje;
DROP TABLE LOW_STRESS_DESIGN.bi_ruta_aerea;
DROP TABLE LOW_STRESS_DESIGN.bi_avion;
DROP TABLE LOW_STRESS_DESIGN.bi_tipo_habitacion;
DROP TABLE LOW_STRESS_DESIGN.bi_ciudad;
DROP TABLE LOW_STRESS_DESIGN.bi_proveedor;
DROP TABLE LOW_STRESS_DESIGN.bi_cliente;
DROP TABLE LOW_STRESS_DESIGN.bi_anio_y_mes;